### ISSUE TITLE
Fix Readme to show how to use it

### ISSUE THREAD

**Issue by borisaguilar** [niphlod/cs_monitor_plugin#12]
Hi! I'm interested on trying this plugin but, i hardly understand how plugins work on web2py and I have not been able to use it (only install it for which instructions are quite clear imho).

**Comment by niphlod** [comment]
it's rather simple: you have your app in the applications/ directory on web2py ....

```
applications/
    yourapp/
          controllers/
               appadmin.py
               default.py
          ........
```

well, you download this and you copy the contents inside your application, so it becomes

```
applications/
    yourapp/
          controllers/
               appadmin.py
               default.py
               plugin_cs_monitor.py
          ...........
```

From there on, at http://your_host:8000/yourapp/plugin_cs_monitor/index you'll see the plugin index page

**Comment by borisaguilar** [comment]
Got it, can i use it without mixing it with my app code (thats what I understood from plugins folder in web2py folders structure) is that possible?
something like:

```
applications/
    yourapp/
          controllers/
               appadmin.py
               default.py
          plugins/
               cs_monitor/
                   controllers/
                           plugin_cs_monitor.py
          ...........
```

**Comment by niphlod** [comment]
Nope. folder structure for plugins is fixed. You can create an empty app with the plugin in it pointing to the same Db, but that's pretty much all your options
