### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by ilvalle** [niphlod/cs_monitor_plugin#3]
I couldn't find out the license for this plugin. 
I would plan to use it in a project

**Comment by niphlod** [comment]
it's LGPL (static/plugin_cs_monitor/license.html) right now. 

Seems fine to you ?

**Comment by ilvalle** [comment]
Yep, sorry I didn't find that file.

 Paolo

2013/3/18 niphlod notifications@github.com

**Comment by niphlod** [comment]
I meant, the LGPL is fine ?

**Comment by ilvalle** [comment]
yes, it is fine for me.
I will use the plugin in a agpl application.

 Paolo

2013/3/18 niphlod notifications@github.com

**Comment by niphlod** [comment]
ok. closing.
