### ISSUE TITLE
Create task from homepage

### ISSUE THREAD

**Issue by ilvalle** [niphlod/cs_monitor_plugin#4]
Hi, I would like to have the possibility to create a task from the first page too.
Right now, visiting application/plugin_cs_monitor/index I haven't found a way to create a task from the web-interface. The user has to write the code to schedule the task programmatically.

**Comment by niphlod** [comment]
uhm, I'll add a shortcut..... to be fair, there is an interface to insert a new task, but the way it's designed right now needs you to reach an existing task and then press the new button (if you reach edit_task/id_of_existing_task/new there's a form ready to be used, with function_name, task_name and group_name prefilled).

Anyway, you're right, there should be a "more accessible" link from the index page, just in case.

**Comment by ilvalle** [comment]
I know that there is the form, the problem is that is to hard to remember
the link :-P

 Paolo

2013/3/18 niphlod notifications@github.com
