### ISSUE TITLE
Sorting table columns

### ISSUE THREAD

**Issue by ilvalle** [niphlod/cs_monitor_plugin#6]
I just came across this https://github.com/DataTables/DataTables
it seems that works well with twitter bootstrap table
It has three license MIT, GPLv2 and BSD; it should be possible to incorporate it in the plugin.

**Comment by niphlod** [comment]
what columns do you need to sort it for (and on which tables) ? 
seems an overkill to add all the logic required and 70KB of javascript for a small integration needed to just sort

**Comment by ilvalle** [comment]
i.e., start/stop time in task view

 Paolo

2013/3/25 niphlod notifications@github.com

**Comment by niphlod** [comment]
fixed by 1.1.0
